name: Default

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    strategy:
      fail-fast: false
      matrix:
        php-versions: ['8.2', '8.3', '8.4']

    steps:
      - uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: '0'  # Fetch all history for accurate coverage reporting
          ref: ${{ github.event_name == 'pull_request' && github.head_ref || github.ref }}

      - name: Setup PHP with PECL extension
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php-versions }}
          tools: composer

      - name: Cache Composer packages
        id: composer-cache
        uses: actions/cache@v4
        with:
          path: vendor
          key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-php-

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress

      - name: Check coding standard
        run: vendor/bin/phpcs -p

      - name: Analyze with PHPStan
        run: vendor/bin/phpstan analyse

      - name: Execute PHPUnit tests
        run: |
          if [ "${{ matrix.php-versions }}" = "8.3" ]; then
            vendor/bin/phpunit --coverage-clover coverage.xml
          else
            vendor/bin/phpunit
          fi

      - name: Generate coverage badge
        if: matrix.php-versions == '8.3'
        uses: timkrase/phpunit-coverage-badge@v1.2.1
        with:
          coverage_badge_path: output/coverage.svg
          push_badge: false
          report: coverage.xml

      - name: Update README badge URL for current repository
        if: matrix.php-versions == '8.3'
        run: |
          # Update the README with the correct badge URL
          sed -i 's|angelov/phpunit-php-vcr|${{ github.repository }}|g' README.md
          if [ "${{ github.event_name }}" = "pull_request" ]; then
            sed -i 's|image-data/coverage.svg|${{ github.head_ref }}/coverage.svg|g' README.md
          fi

      - name: Check badge file exists (main branch)
        if: matrix.php-versions == '8.3' && github.ref == 'refs/heads/main'
        id: check_badge
        run: |
          if [ -f "output/coverage.svg" ]; then
            echo "badge_exists=true" >> $GITHUB_OUTPUT
          else
            echo "badge_exists=false" >> $GITHUB_OUTPUT
            echo "Coverage badge file not found, skipping push to image-data branch"
          fi

      - name: Deploy badge to image-data branch
        if: matrix.php-versions == '8.3' && github.ref == 'refs/heads/main' && steps.check_badge.outputs.badge_exists == 'true'
        uses: peaceiris/actions-gh-pages@v3
        with:
          publish_dir: ./output
          publish_branch: image-data
          github_token: ${{ secrets.GITHUB_TOKEN }}
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'

      - name: Commit coverage badge to current branch (PR)
        if: matrix.php-versions == '8.3'
        run: |
          echo "Event name: ${{ github.event_name }}"
          # Check if badge file exists
          if [ ! -f "output/coverage.svg" ]; then
            echo "Coverage badge file not found, skipping commit"
            exit 0
          fi

          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"
          # Copy coverage badge to root for PR commits
          cp output/coverage.svg coverage.svg
          git add coverage.svg
          git commit -m "ci: Update coverage badge" || exit 0
          git push
